# Generated by Django 3.0.3 on 2020-08-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.IntegerField()),
                ('id_alumno', models.IntegerField()),
            ],
        ),
    ]
