# Generated by Django 3.1 on 2020-09-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=400)),
            ],
        ),
    ]
