# Generated by Django 3.0.3 on 2020-08-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='curso_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
