# Generated by Django 3.1 on 2020-10-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_archivo_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='uploaded_at',
        ),
    ]
