# Generated by Django 3.0.3 on 2020-03-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_paciente_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo',
            field=models.CharField(default='Vacio', max_length=30),
        ),
    ]
