# Generated by Django 3.0.3 on 2020-07-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_paciente_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='f_nacimiento',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='num_domicilio',
        ),
    ]
