# Generated by Django 3.0.3 on 2020-07-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20200727_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='file',
        ),
    ]
