# Generated by Django 3.0.3 on 2020-07-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200727_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
