# Generated by Django 3.0.3 on 2020-07-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_delete_paciente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutor',
            new_name='Alumno',
        ),
    ]
