# Generated by Django 3.0.3 on 2020-07-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20200727_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal',
            new_name='Docente',
        ),
    ]
